name: Stoch RSI

on:
  schedule: [{cron:'*/15 * * * *'}]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version:'3.11',cache:'pip'}
      - run: |
          pip install -r requirements.txt
      - name: download cache
        uses: actions/download-artifact@v4
        with: {name:alert-cache}
        continue-on-error: true
      - name: run
        env:
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: python main.py
      - name: Upload cache
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: alert-cache
          path: alert_cache.json
          if-no-files-found: ignore
          retention-days: 7

